version: "3.8"
services:
  # web:
  #   build: .
  #   depends_on: 
  #     db:
  #       condition: service_healthy
  #       restart: true
  #   ports:
  #     - '5000:5000'
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'sawang_sao2023'
      MYSQL_USER: 'sawang_sao2023'
      MYSQL_PASSWORD: 'P@ssw0rd'
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
    ports:
      - '3326:3306'
    volumes:
      - ./volume_db/initdb:/docker-entrypoint-initdb.d
      - ./volume_db/dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://db:3306"]
      interval: 3s
      timeout: 1s
      retries: 1
      start_period: 2s

volumes:
  volume_db: